/*==============================================================
 File Name        : D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET.sql
 Object Name      : AEROSPACE_PARTS_TARGET
 Project          : SCRUM-154
 Purpose          : Target table DDL - Aerospace Parts Inventory
 Generated By     : AI Skill - SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-154
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        ADAPT delta: +INVENTORY_PRIORITY_LEVEL
==============================================================*/
CREATE OR ALTER TABLE D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET (
    PART_NUMBER              VARCHAR(100)    NOT NULL,
    PART_NAME                VARCHAR(500),
    PART_DESCRIPTION         VARCHAR(2000),
    MANUFACTURER             VARCHAR(300),
    PART_CATEGORY            VARCHAR(200),
    WEIGHT_KG                NUMBER(12,4),
    UNIT_PRICE_USD           NUMBER(18,2),
    QUANTITY_AVAILABLE       NUMBER(12),
    QUANTITY_ON_HAND         NUMBER(12),
    CERTIFICATION_STATUS     VARCHAR(50),
    LEAD_TIME_DAYS           NUMBER(10),
    SUPPLIER_CODE            VARCHAR(100),
    COUNTRY_OF_ORIGIN        VARCHAR(100),
    WAREHOUSE_LOCATION       VARCHAR(200),
    REORDER_POINT            NUMBER(12),
    CREATED_AT               TIMESTAMP_NTZ,
    UPDATED_AT               TIMESTAMP_NTZ,
    RISK_SCORE               VARCHAR(20),
    SUPPLY_RISK_LEVEL        VARCHAR(20),
    PROCUREMENT_PRIORITY     VARCHAR(20),
    OPERATIONAL_CRITICALITY  VARCHAR(50),
    RECORD_STATUS            VARCHAR(20)     DEFAULT 'Active',
    ETL_LOAD_TIMESTAMP       TIMESTAMP_NTZ,
    ETL_RUN_ID               VARCHAR(36),
    ETL_BATCH_ID             VARCHAR(36),
    INVENTORY_PRIORITY_LEVEL VARCHAR(20)     -- [DELTA ADD] New derived column per BRD BR-009
);