/*==============================================================
 File Name        : D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET.sql
 Object Name      : AEROSPACE_PARTS_TARGET
 Project          : SCRUM-152
 Purpose          : Target table DDL — Aerospace Parts Inventory analytics store
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-152
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        ADAPT delta: +OPERATIONAL_CRITICALITY column per BRD BR-008
==============================================================*/
CREATE OR ALTER TABLE D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)  NOT NULL,
    PART_NAME               VARCHAR(500),
    PART_DESCRIPTION        VARCHAR(2000),
    MANUFACTURER            VARCHAR(300),
    PART_CATEGORY           VARCHAR(200),
    WEIGHT_KG               NUMBER(12,4),
    UNIT_PRICE_USD          NUMBER(18,2),
    QUANTITY_AVAILABLE      NUMBER(12,0),
    QUANTITY_ON_HAND        NUMBER(12,0),
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    SUPPLIER_CODE           VARCHAR(100),
    COUNTRY_OF_ORIGIN       VARCHAR(100),
    WAREHOUSE_LOCATION      VARCHAR(200),
    REORDER_POINT           NUMBER(12,0),
    CREATED_AT              TIMESTAMP_NTZ,
    UPDATED_AT              TIMESTAMP_NTZ,
    RISK_SCORE              VARCHAR(20),
    SUPPLY_RISK_LEVEL       VARCHAR(20),
    PROCUREMENT_PRIORITY    VARCHAR(20),
    RECORD_STATUS           VARCHAR(20)   DEFAULT 'Active',
    ETL_LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    ETL_RUN_ID              VARCHAR(36),
    ETL_BATCH_ID            VARCHAR(36),
    OPERATIONAL_CRITICALITY VARCHAR(30)   -- [DELTA ADD] OPERATIONAL_CRITICALITY: new derived column per BRD BR-008 — classifies parts by operational importance
);