/*==============================================================
 File Name        : D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_INVENTORY_PIPELINE.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE
 Project          : SCRUM-152
 Purpose          : Incremental SCD1 pipeline — AEROSPACE_PARTS_SOURCE to AEROSPACE_PARTS_TARGET
                    Implements: UPDATED_AT watermark, ROW_NUMBER dedup, UPPER(MANUFACTURER),
                    WEIGHT_KG sentinel, RISK_SCORE CASE, OPERATIONAL_CRITICALITY CASE,
                    SCD1 MERGE, soft delete, ETL_RECONCILIATION_LOG per run
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-152
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        ADAPT delta: +OPERATIONAL_CRITICALITY derived column (BR-008)
                             Adapted from: AEROSPACE_PARTS_INVENTORY_PIPELINE (90% match)
==============================================================*/
-- [DELTA REFERENCE] Adapted from: AEROSPACE_PARTS_INVENTORY_PIPELINE (Object Registry, 90% match, ADAPT route)
CREATE OR REPLACE PROCEDURE D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_INVENTORY_PIPELINE(P_MODE VARCHAR DEFAULT 'INCREMENTAL')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
DECLARE
    v_run_id             VARCHAR;
    v_batch_id           VARCHAR;
    v_last_ts            TIMESTAMP_NTZ;
    v_source_count       NUMBER;
    v_pre_merge_count    NUMBER;
    v_insert_count       NUMBER;
    v_update_count       NUMBER;
    v_soft_delete_count  NUMBER;
    v_start_ts           TIMESTAMP_NTZ;
    v_exec_seconds       NUMBER;
    v_status             VARCHAR;
    v_error_msg          VARCHAR;
BEGIN
    v_run_id   := UUID_STRING();
    v_batch_id := UUID_STRING();
    v_start_ts := CURRENT_TIMESTAMP();
    v_status   := 'SUCCESS';

    -- ── WATERMARK: Resolve last successful run timestamp ────────────────────
    IF (P_MODE = 'INCREMENTAL') THEN
        SELECT COALESCE(MAX(RUN_TIMESTAMP), '1900-01-01'::TIMESTAMP_NTZ) INTO :v_last_ts
        FROM D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.ETL_RECONCILIATION_LOG
        WHERE TARGET_TABLE = 'AEROSPACE_PARTS_TARGET' AND STATUS = 'SUCCESS';
    ELSE
        v_last_ts := '1900-01-01'::TIMESTAMP_NTZ;
    END IF;

    -- ── DEDUPLICATION + TRANSFORMATIONS: Stage deduplicated source records ──
    CREATE OR REPLACE TEMPORARY TABLE DEDUPED_SOURCE AS
    SELECT
        PART_NUMBER,
        PART_NAME,
        PART_DESCRIPTION,
        UPPER(MANUFACTURER)                         AS MANUFACTURER,
        PART_CATEGORY,
        CASE WHEN WEIGHT_KG <= 0 THEN -1 ELSE WEIGHT_KG END AS WEIGHT_KG,
        ROUND(UNIT_PRICE_USD, 2)                    AS UNIT_PRICE_USD,
        QUANTITY_AVAILABLE,
        QUANTITY_ON_HAND,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        SUPPLIER_CODE,
        COUNTRY_OF_ORIGIN,
        WAREHOUSE_LOCATION,
        REORDER_POINT,
        CREATED_AT,
        UPDATED_AT,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 100 THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'Low Risk'
            ELSE 'Medium Risk'
        END AS RISK_SCORE,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 100 THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'Low Risk'
            ELSE 'Medium Risk'
        END AS SUPPLY_RISK_LEVEL,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60                            THEN 'CRITICAL'
            WHEN (CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 100) AND LEAD_TIME_DAYS > 60  THEN 'HIGH'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60              THEN 'STANDARD'
            ELSE 'MONITOR'
        END AS PROCUREMENT_PRIORITY,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60 AND QUANTITY_AVAILABLE <= REORDER_POINT THEN 'Mission Critical'       -- [DELTA ADD] OPERATIONAL_CRITICALITY: High Risk + stock below reorder = Mission Critical per BRD BR-008
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60                                         THEN 'Safety Critical'         -- [DELTA ADD] OPERATIONAL_CRITICALITY: High Risk = Safety Critical per BRD BR-008
            WHEN (CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 100) AND QUANTITY_AVAILABLE <= REORDER_POINT THEN 'Operationally Important' -- [DELTA ADD] OPERATIONAL_CRITICALITY: Medium Risk + stock below reorder = Operationally Important per BRD BR-008
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60               THEN 'Standard'                            -- [DELTA ADD] OPERATIONAL_CRITICALITY: Low Risk + valid cert = Standard per BRD BR-008
            ELSE 'Non-Critical'
        END AS OPERATIONAL_CRITICALITY,
        'Active' AS RECORD_STATUS
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
        FROM D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT > :v_last_ts
    ) t
    WHERE RN = 1;

    SELECT COUNT(*) INTO :v_source_count FROM DEDUPED_SOURCE;
    SELECT COUNT(*) INTO :v_pre_merge_count
    FROM D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET TGT
    INNER JOIN DEDUPED_SOURCE SRC ON TGT.PART_NUMBER = SRC.PART_NUMBER;
    v_update_count := v_pre_merge_count;
    v_insert_count := v_source_count - v_pre_merge_count;

    -- ── SCD TYPE 1 MERGE: Overwrite matched records, insert new ─────────────
    MERGE INTO D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET AS TGT
    USING DEDUPED_SOURCE AS SRC
    ON TGT.PART_NUMBER = SRC.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        TGT.PART_NAME              = SRC.PART_NAME,
        TGT.PART_DESCRIPTION       = SRC.PART_DESCRIPTION,
        TGT.MANUFACTURER           = SRC.MANUFACTURER,
        TGT.PART_CATEGORY          = SRC.PART_CATEGORY,
        TGT.WEIGHT_KG              = SRC.WEIGHT_KG,
        TGT.UNIT_PRICE_USD         = SRC.UNIT_PRICE_USD,
        TGT.QUANTITY_AVAILABLE     = SRC.QUANTITY_AVAILABLE,
        TGT.QUANTITY_ON_HAND       = SRC.QUANTITY_ON_HAND,
        TGT.CERTIFICATION_STATUS   = SRC.CERTIFICATION_STATUS,
        TGT.LEAD_TIME_DAYS         = SRC.LEAD_TIME_DAYS,
        TGT.SUPPLIER_CODE          = SRC.SUPPLIER_CODE,
        TGT.COUNTRY_OF_ORIGIN      = SRC.COUNTRY_OF_ORIGIN,
        TGT.WAREHOUSE_LOCATION     = SRC.WAREHOUSE_LOCATION,
        TGT.REORDER_POINT          = SRC.REORDER_POINT,
        TGT.CREATED_AT             = SRC.CREATED_AT,
        TGT.UPDATED_AT             = SRC.UPDATED_AT,
        TGT.RISK_SCORE             = SRC.RISK_SCORE,
        TGT.SUPPLY_RISK_LEVEL      = SRC.SUPPLY_RISK_LEVEL,
        TGT.PROCUREMENT_PRIORITY   = SRC.PROCUREMENT_PRIORITY,
        TGT.OPERATIONAL_CRITICALITY = SRC.OPERATIONAL_CRITICALITY, -- [DELTA ADD] OPERATIONAL_CRITICALITY: added to MERGE WHEN MATCHED UPDATE per BR-008
        TGT.RECORD_STATUS          = SRC.RECORD_STATUS,
        TGT.ETL_LOAD_TIMESTAMP     = CURRENT_TIMESTAMP(),
        TGT.ETL_RUN_ID             = :v_run_id,
        TGT.ETL_BATCH_ID           = :v_batch_id
    WHEN NOT MATCHED THEN INSERT
        (PART_NUMBER, PART_NAME, PART_DESCRIPTION, MANUFACTURER, PART_CATEGORY,
         WEIGHT_KG, UNIT_PRICE_USD, QUANTITY_AVAILABLE, QUANTITY_ON_HAND,
         CERTIFICATION_STATUS, LEAD_TIME_DAYS, SUPPLIER_CODE, COUNTRY_OF_ORIGIN,
         WAREHOUSE_LOCATION, REORDER_POINT, CREATED_AT, UPDATED_AT,
         RISK_SCORE, SUPPLY_RISK_LEVEL, PROCUREMENT_PRIORITY,
         OPERATIONAL_CRITICALITY, -- [DELTA ADD] OPERATIONAL_CRITICALITY: added to MERGE WHEN NOT MATCHED INSERT per BR-008
         RECORD_STATUS, ETL_LOAD_TIMESTAMP, ETL_RUN_ID, ETL_BATCH_ID)
    VALUES
        (SRC.PART_NUMBER, SRC.PART_NAME, SRC.PART_DESCRIPTION, SRC.MANUFACTURER, SRC.PART_CATEGORY,
         SRC.WEIGHT_KG, SRC.UNIT_PRICE_USD, SRC.QUANTITY_AVAILABLE, SRC.QUANTITY_ON_HAND,
         SRC.CERTIFICATION_STATUS, SRC.LEAD_TIME_DAYS, SRC.SUPPLIER_CODE, SRC.COUNTRY_OF_ORIGIN,
         SRC.WAREHOUSE_LOCATION, SRC.REORDER_POINT, SRC.CREATED_AT, SRC.UPDATED_AT,
         SRC.RISK_SCORE, SRC.SUPPLY_RISK_LEVEL, SRC.PROCUREMENT_PRIORITY,
         SRC.OPERATIONAL_CRITICALITY,
         SRC.RECORD_STATUS, CURRENT_TIMESTAMP(), :v_run_id, :v_batch_id);

    -- ── SOFT DELETE: Mark absent source records as Decommissioned ───────────
    UPDATE D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_TARGET
    SET RECORD_STATUS      = 'Decommissioned',
        ETL_LOAD_TIMESTAMP = CURRENT_TIMESTAMP(),
        ETL_RUN_ID         = :v_run_id,
        ETL_BATCH_ID       = :v_batch_id
    WHERE PART_NUMBER NOT IN (SELECT PART_NUMBER FROM D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_SOURCE)
      AND RECORD_STATUS != 'Decommissioned';
    v_soft_delete_count := SQLROWCOUNT;

    SELECT DATEDIFF('second', :v_start_ts, CURRENT_TIMESTAMP()) INTO :v_exec_seconds;

    -- ── RECONCILIATION: Log run metrics per BRD RULE-012 ───────────────────
    INSERT INTO D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.ETL_RECONCILIATION_LOG
        (RUN_ID, RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, SOURCE_COUNT,
         INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT, STATUS, EXECUTION_SECONDS)
    VALUES
        (:v_run_id, :v_start_ts, 'AEROSPACE_PARTS_SOURCE', 'AEROSPACE_PARTS_TARGET',
         :v_source_count, :v_insert_count, :v_update_count, :v_soft_delete_count, :v_status, :v_exec_seconds);

    RETURN 'SUCCESS | RUN_ID=' || :v_run_id || ' | BATCH=' || :v_batch_id
        || ' | SOURCE=' || :v_source_count || ' | INSERTS=' || :v_insert_count
        || ' | UPDATES=' || :v_update_count || ' | SOFT_DELETES=' || :v_soft_delete_count
        || ' | SECS=' || :v_exec_seconds;

EXCEPTION WHEN OTHER THEN
    -- ── ERROR HANDLING: Log failure and return error details ────────────────
    v_error_msg := SQLERRM;
    INSERT INTO D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.ETL_RECONCILIATION_LOG
        (RUN_ID, RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE,
         SOURCE_COUNT, INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT, STATUS, ERROR_MESSAGE)
    VALUES
        (:v_run_id, :v_start_ts, 'AEROSPACE_PARTS_SOURCE', 'AEROSPACE_PARTS_TARGET',
         0, 0, 0, 0, 'FAILED', :v_error_msg);
    RETURN 'FAILED | RUN_ID=' || :v_run_id || ' | ERROR=' || :v_error_msg;
END;
$$;