/*==============================================================
 File Name        : D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
 Project          : SCRUM-152
 Purpose          : Scheduled task — Daily 05:00 UTC for AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-152
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        ADAPT: task created for daily 05:00 UTC CRON schedule
==============================================================*/
CREATE OR REPLACE TASK D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
  WAREHOUSE = W_IN_CAPG_BIONIC_PMI_POC_XS
  SCHEDULE = 'USING CRON 0 5 * * * UTC'
AS CALL D_IN_CAPG_BIONIC_PMI_POC.PMI_AGENT.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');