/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
 Project          : SCRUM-138
 Purpose          : Scheduled task — Daily at 08:00 UTC invoking AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-09-28
 Work Item        : SCRUM-138
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-28  AI Skill        ADAPT: Recreate scheduled task for updated AEROSPACE_PARTS_INVENTORY_PIPELINE (SCRUM-138)
==============================================================*/
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
  WAREHOUSE = W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS
  SCHEDULE = 'USING CRON 0 8 * * * UTC'
AS CALL IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');