/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_TASK
 Project          : SCRUM-136
 Purpose          : Scheduled task -- Daily 02:00 UTC for AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill -- SDLC
 Generated Date   : 2026-09-28
 Work Item        : SCRUM-136
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-28  AI Skill        ADAPT delta: RECREATE task with CRON 0 2 * * * UTC
==============================================================*/
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_TASK
  WAREHOUSE = SNOWFLAKE_LEARNING_WH
  SCHEDULE  = 'USING CRON 0 2 * * * UTC'
AS CALL IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');