/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET.sql
 Object Name      : AEROSPACE_PARTS_TARGET
 Project          : SCRUM-137
 Purpose          : Target table DDL - Aerospace Parts Inventory pipeline target
 Generated By     : AI Skill - SDLC
 Generated Date   : 2026-09-28
 Work Item        : SCRUM-137
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT delta: +EXECUTION_DURATION_SECONDS to ETL_RECONCILIATION_LOG
 2026-09-25  AI Skill        ADAPT delta: MANUFACTURER UPPER->INITCAP, RISK_SCORE thresholds
 2026-09-28  AI Skill        ADAPT delta: +STOCK_QUANTITY, +SUPPLY_RISK_LEVEL, +SUPPLIER_COUNT
==============================================================*/
CREATE OR ALTER TABLE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET (
    PART_NUMBER              VARCHAR(100)     NOT NULL,
    PART_NAME                VARCHAR(500),
    MANUFACTURER             VARCHAR(300),
    WEIGHT_KG                NUMBER(12,4),
    CERTIFICATION_STATUS     VARCHAR(50),
    LEAD_TIME_DAYS           NUMBER(10),
    UNIT_PRICE_USD           NUMBER(18,2),
    CATEGORY                 VARCHAR(200),
    SUPPLIER_ID              VARCHAR(100),
    UPDATED_AT               TIMESTAMP_NTZ,
    RISK_SCORE               VARCHAR(20),
    INVENTORY_HEALTH_STATUS  VARCHAR(50),
    LOAD_TIMESTAMP           TIMESTAMP_NTZ,
    PART_STATUS              VARCHAR(50)      DEFAULT 'Active',
    LIFECYCLE_STATUS         VARCHAR(50),
    INSTALLATION_DATE        DATE,
    QUANTITY_ON_HAND         NUMBER(12),
    STOCK_QUANTITY           NUMBER(10,0),
    SUPPLY_RISK_LEVEL        VARCHAR(10),
    SUPPLIER_COUNT           NUMBER(5,0)
);