/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE
 Project          : SCRUM-138
 Purpose          : Incremental SCD Type 1 pipeline from AEROSPACE_PARTS_SOURCE to
                    AEROSPACE_PARTS_TARGET — UPPER(MANUFACTURER), corrected RISK_SCORE
                    thresholds, NULL sentinel for WEIGHT_KG, STATUS soft-delete,
                    ETL_LOAD_TIMESTAMP and ETL_RUN_ID audit columns per BRD SCRUM-138
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-09-28
 Work Item        : SCRUM-138
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-25  AI Skill        ADAPT delta: +EXECUTION_DURATION_SECONDS to ETL_RECONCILIATION_LOG
 2026-09-25  AI Skill        ADAPT delta: MANUFACTURER UPPER->INITCAP, RISK_SCORE thresholds >90 and <=70, +INVENTORY_HEALTH_STATUS
 2026-09-28  AI Skill        ADAPT delta: MANUFACTURER INITCAP->UPPER, WEIGHT_KG IFF-sentinel->NULL, RISK_SCORE thresholds corrected
 2026-09-28  AI Skill        ADAPT delta: MANUFACTURER UPPER->INITCAP, WEIGHT_KG NULL->-1, +STOCK_QUANTITY, +SUPPLY_RISK_LEVEL
 2026-09-28  AI Skill        ADAPT delta: MANUFACTURER INITCAP->UPPER, WEIGHT_KG -1->NULL, RISK_SCORE BRD-correct, STATUS->Decommissioned, LOAD_TIMESTAMP->ETL_LOAD_TIMESTAMP, +ETL_RUN_ID
==============================================================*/
-- [DELTA REFERENCE] Adapted from: IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE
CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE(P_MODE VARCHAR DEFAULT 'INCREMENTAL')
RETURNS VARCHAR
LANGUAGE SQL
AS $$
DECLARE
    v_last_ts                 TIMESTAMP_NTZ;
    v_pipeline_start          TIMESTAMP_NTZ;
    v_load_mode               VARCHAR        DEFAULT 'INCREMENTAL';
    v_source_count            NUMBER         DEFAULT 0;
    v_target_count            NUMBER         DEFAULT 0;
    v_inserted_count          NUMBER         DEFAULT 0;
    v_updated_count           NUMBER         DEFAULT 0;
    v_decommissioned_count    NUMBER         DEFAULT 0;
    v_matched_count           NUMBER         DEFAULT 0;
    v_execution_duration      NUMBER         DEFAULT 0;
    v_etl_run_id              VARCHAR        DEFAULT UUID_STRING();
BEGIN
    -- == Watermark Lookup ==
    v_pipeline_start := CURRENT_TIMESTAMP();
    IF (P_MODE = 'FULL') THEN
        v_last_ts   := '1900-01-01'::TIMESTAMP_NTZ;
        v_load_mode := 'FULL';
    ELSE
        SELECT COALESCE(MAX(RUN_TIMESTAMP), '1900-01-01'::TIMESTAMP_NTZ)
          INTO :v_last_ts
          FROM IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG
         WHERE PIPELINE_NAME = 'AEROSPACE_PARTS_INVENTORY_PIPELINE'
           AND STATUS = 'COMPLETED';
        v_load_mode := 'INCREMENTAL';
    END IF;
    -- == Extract + Deduplicate + Transform ==
    CREATE OR REPLACE TEMPORARY TABLE AEROSPACE_PARTS_STAGE AS
    SELECT
        PART_NUMBER,
        PART_NAME,
        UPPER(MANUFACTURER)                                                 AS MANUFACTURER,
        -- [DELTA MODIFY] MANUFACTURER: INITCAP -> UPPER per BRD RULE-006
        CATEGORY,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        ROUND(UNIT_PRICE_USD, 2)                                            AS UNIT_PRICE_USD,
        -- [DELTA MODIFY] UNIT_PRICE_USD: confirmed ROUND(2) per BRD STTM
        CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END              AS WEIGHT_KG,
        -- [DELTA MODIFY] WEIGHT_KG: sentinel -1 -> NULL per BRD validation rule
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UPDATED_AT,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 60  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 90  THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'Low Risk'
            ELSE 'Medium Risk'
        END                                                                 AS RISK_SCORE,
        -- [DELTA MODIFY] RISK_SCORE: corrected BRD thresholds — Pending+>60=High, Pending OR >90=Medium, cert+<=60=Low
        CURRENT_TIMESTAMP()                                                 AS ETL_LOAD_TIMESTAMP,
        -- [DELTA RENAME] LOAD_TIMESTAMP -> ETL_LOAD_TIMESTAMP per BRD STTM audit column naming
        :v_etl_run_id                                                       AS ETL_RUN_ID
        -- [DELTA ADD] ETL_RUN_ID: new audit column UUID_STRING() per BRD STTM
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
          FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE
         WHERE UPDATED_AT > :v_last_ts
    ) deduped
    WHERE RN = 1;
    -- == Row Count Pre-Merge ==
    SELECT COUNT(*) INTO :v_source_count   FROM AEROSPACE_PARTS_STAGE;
    SELECT COUNT(*) INTO :v_target_count   FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET;
    SELECT COUNT(*) INTO :v_inserted_count FROM AEROSPACE_PARTS_STAGE stg
     WHERE NOT EXISTS (SELECT 1 FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt WHERE tgt.PART_NUMBER = stg.PART_NUMBER);
    SELECT COUNT(*) INTO :v_updated_count  FROM AEROSPACE_PARTS_STAGE stg
     WHERE     EXISTS (SELECT 1 FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt WHERE tgt.PART_NUMBER = stg.PART_NUMBER);
    v_matched_count := :v_source_count;
    -- == SCD Type 1 Merge ==
    MERGE INTO IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET tgt
    USING AEROSPACE_PARTS_STAGE src ON tgt.PART_NUMBER = src.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        tgt.PART_NAME            = src.PART_NAME,
        tgt.MANUFACTURER         = src.MANUFACTURER,
        tgt.CATEGORY             = src.CATEGORY,
        tgt.CERTIFICATION_STATUS = src.CERTIFICATION_STATUS,
        tgt.LEAD_TIME_DAYS       = src.LEAD_TIME_DAYS,
        tgt.UNIT_PRICE_USD       = src.UNIT_PRICE_USD,
        tgt.WEIGHT_KG            = src.WEIGHT_KG,
        tgt.STOCK_QUANTITY       = src.STOCK_QUANTITY,
        tgt.SUPPLIER_ID          = src.SUPPLIER_ID,
        tgt.UPDATED_AT           = src.UPDATED_AT,
        tgt.RISK_SCORE           = src.RISK_SCORE,
        tgt.STATUS               = 'Active',
        -- [DELTA MODIFY] STATUS: soft-delete field aligned to BRD RULE-005 (STATUS not PART_STATUS)
        tgt.ETL_LOAD_TIMESTAMP   = src.ETL_LOAD_TIMESTAMP,
        -- [DELTA RENAME] LOAD_TIMESTAMP -> ETL_LOAD_TIMESTAMP in MERGE UPDATE
        tgt.ETL_RUN_ID           = src.ETL_RUN_ID
        -- [DELTA ADD] ETL_RUN_ID in MERGE UPDATE per BRD STTM
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, PART_NAME, MANUFACTURER, CATEGORY, CERTIFICATION_STATUS,
        LEAD_TIME_DAYS, UNIT_PRICE_USD, WEIGHT_KG, STOCK_QUANTITY, SUPPLIER_ID,
        UPDATED_AT, RISK_SCORE, STATUS, ETL_LOAD_TIMESTAMP, ETL_RUN_ID
    ) VALUES (
        src.PART_NUMBER, src.PART_NAME, src.MANUFACTURER, src.CATEGORY, src.CERTIFICATION_STATUS,
        src.LEAD_TIME_DAYS, src.UNIT_PRICE_USD, src.WEIGHT_KG, src.STOCK_QUANTITY, src.SUPPLIER_ID,
        src.UPDATED_AT, src.RISK_SCORE, 'Active', src.ETL_LOAD_TIMESTAMP, src.ETL_RUN_ID
    );
    -- == Soft Delete ==
    UPDATE IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_TARGET
       SET STATUS             = 'Decommissioned',
           -- [DELTA MODIFY] STATUS: field renamed PART_STATUS -> STATUS, value = Decommissioned per BRD RULE-005
           ETL_LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
     WHERE STATUS <> 'Decommissioned'
       AND PART_NUMBER NOT IN (SELECT PART_NUMBER FROM IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_SOURCE);
    v_decommissioned_count := SQLROWCOUNT;
    -- == Reconciliation Log ==
    v_execution_duration := DATEDIFF('second', :v_pipeline_start, CURRENT_TIMESTAMP());
    INSERT INTO IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
        RECON_ID, PIPELINE_NAME, RUN_TIMESTAMP, SOURCE_COUNT, TARGET_COUNT, MATCHED_COUNT,
        INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT, LOAD_MODE, STATUS, NOTES, EXECUTION_DURATION_SECONDS
    ) VALUES (
        UUID_STRING(), 'AEROSPACE_PARTS_INVENTORY_PIPELINE', CURRENT_TIMESTAMP(),
        :v_source_count, :v_target_count, :v_matched_count, :v_inserted_count, :v_updated_count, :v_decommissioned_count,
        :v_load_mode, 'COMPLETED', 'Pipeline completed successfully. Mode: ' || :v_load_mode, :v_execution_duration
    );
    RETURN 'SUCCESS: Mode=' || :v_load_mode
        || ' | Source='        || :v_source_count::VARCHAR
        || ' | Inserted='      || :v_inserted_count::VARCHAR
        || ' | Updated='       || :v_updated_count::VARCHAR
        || ' | Decommissioned='|| :v_decommissioned_count::VARCHAR
        || ' | Duration(s)='   || :v_execution_duration::VARCHAR;
EXCEPTION WHEN OTHER THEN
    INSERT INTO IDEA_2_DB.PUBLIC.ETL_RECONCILIATION_LOG (
        RECON_ID, PIPELINE_NAME, RUN_TIMESTAMP, SOURCE_COUNT, TARGET_COUNT, MATCHED_COUNT,
        INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT, LOAD_MODE, STATUS, NOTES, EXECUTION_DURATION_SECONDS
    ) VALUES (
        UUID_STRING(), 'AEROSPACE_PARTS_INVENTORY_PIPELINE', CURRENT_TIMESTAMP(),
        :v_source_count, :v_target_count, 0, 0, 0, 0,
        :v_load_mode, 'FAILED', 'Pipeline failed: ' || SQLERRM,
        DATEDIFF('second', :v_pipeline_start, CURRENT_TIMESTAMP())
    );
    RETURN 'ERROR: ' || SQLERRM;
END;
$$;