/*==============================================================
 File Name        : IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK.sql
 Object Name      : AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
 Project          : SCRUM-137
 Purpose          : Scheduled task - Daily 05:00 UTC for AEROSPACE_PARTS_INVENTORY_PIPELINE
 Generated By     : AI Skill - SDLC
 Generated Date   : 2026-09-28
 Work Item        : SCRUM-137
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-09-28  AI Skill        ADAPT delta: Recreated task for updated AEROSPACE_PARTS_INVENTORY_PIPELINE with SUPPLY_RISK_LEVEL
==============================================================*/
CREATE OR REPLACE TASK IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE_TASK
  WAREHOUSE = SNOWFLAKE_LEARNING_WH
  SCHEDULE = 'USING CRON 0 5 * * * UTC'
AS CALL IDEA_2_DB.PUBLIC.AEROSPACE_PARTS_INVENTORY_PIPELINE('INCREMENTAL');